name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-push-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: actions/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD  }}